// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface AgroTypes$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "AgroTypes";
  readonly sourceName: "contracts/AgroTypes.sol";
  readonly abi: [];
  readonly bytecode: "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212205506e632a9eed2f7c33b6b4ba85adde09eadba1cf78dd9db2a1213505092656e64736f6c63430008180033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212205506e632a9eed2f7c33b6b4ba85adde09eadba1cf78dd9db2a1213505092656e64736f6c63430008180033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/AgroTypes.sol";
  readonly buildInfoId: "solc-0_8_24-e21c2f5703c23a886933be0a1696d0986e80bbe6";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["AgroTypes"]: AgroTypes$Type;
    ["contracts/AgroTypes.sol:AgroTypes"]: AgroTypes$Type;
  }
}