// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface AgroTypes$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "AgroTypes";
  readonly sourceName: "contracts/AgroTypes.sol";
  readonly abi: [];
  readonly bytecode: "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212204a502503069a20005c71414930ce4fa201ca1f102b9b35601f01ded13300505264736f6c63430008180033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212204a502503069a20005c71414930ce4fa201ca1f102b9b35601f01ded13300505264736f6c63430008180033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/AgroTypes.sol";
  readonly buildInfoId: "solc-0_8_24-1ee7af3e5cdc6d02f3b2ae82dd9b44c20ad95b09";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["AgroTypes"]: AgroTypes$Type;
    ["contracts/AgroTypes.sol:AgroTypes"]: AgroTypes$Type;
  }
}