// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Placeholder$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Placeholder";
  readonly sourceName: "contracts/Placeholder.sol";
  readonly abi: [];
  readonly bytecode: "0x6080604052348015600e575f80fd5b50603e80601a5f395ff3fe60806040525f80fdfea2646970667358221220ecd55c10a55e1ce3905982a38f9fdba9b8143e0b1740d493613aac30627644ca64736f6c63430008180033";
  readonly deployedBytecode: "0x60806040525f80fdfea2646970667358221220ecd55c10a55e1ce3905982a38f9fdba9b8143e0b1740d493613aac30627644ca64736f6c63430008180033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/Placeholder.sol";
  readonly buildInfoId: "solc-0_8_24-1ee7af3e5cdc6d02f3b2ae82dd9b44c20ad95b09";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Placeholder"]: Placeholder$Type;
    ["contracts/Placeholder.sol:Placeholder"]: Placeholder$Type;
  }
}