/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface AccessControlInterface extends Interface {
    getFunction(nameOrSignature: "authorizedViewersGroupId" | "configureSemaphore" | "hasUsedNullifier" | "owner" | "recordAccess" | "renounceOwnership" | "semaphoreAddress" | "transferOwnership" | "usedNullifiers"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AccessGranted" | "AccessRevoked" | "OwnershipTransferred" | "SemaphoreConfigured"): EventFragment;

    encodeFunctionData(functionFragment: 'authorizedViewersGroupId', values?: undefined): string;
encodeFunctionData(functionFragment: 'configureSemaphore', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'hasUsedNullifier', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'recordAccess', values: [BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'semaphoreAddress', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'usedNullifiers', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'authorizedViewersGroupId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'configureSemaphore', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasUsedNullifier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordAccess', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'semaphoreAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usedNullifiers', data: BytesLike): Result;
  }

  
    export namespace AccessGrantedEvent {
      export type InputTuple = [nullifier: BigNumberish, dataHash: BytesLike];
      export type OutputTuple = [nullifier: bigint, dataHash: string];
      export interface OutputObject {nullifier: bigint, dataHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AccessRevokedEvent {
      export type InputTuple = [viewer: AddressLike];
      export type OutputTuple = [viewer: string];
      export interface OutputObject {viewer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SemaphoreConfiguredEvent {
      export type InputTuple = [semaphoreAddress: AddressLike, groupId: BigNumberish];
      export type OutputTuple = [semaphoreAddress: string, groupId: bigint];
      export interface OutputObject {semaphoreAddress: string, groupId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AccessControl extends BaseContract {
    
    connect(runner?: ContractRunner | null): AccessControl;
    waitForDeployment(): Promise<this>;

    interface: AccessControlInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    authorizedViewersGroupId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    configureSemaphore: TypedContractMethod<
      [_semaphoreAddress: AddressLike, _groupId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    hasUsedNullifier: TypedContractMethod<
      [nullifier: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    recordAccess: TypedContractMethod<
      [nullifier: BigNumberish, dataHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    semaphoreAddress: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    usedNullifiers: TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'authorizedViewersGroupId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'configureSemaphore'): TypedContractMethod<
      [_semaphoreAddress: AddressLike, _groupId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasUsedNullifier'): TypedContractMethod<
      [nullifier: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'recordAccess'): TypedContractMethod<
      [nullifier: BigNumberish, dataHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'semaphoreAddress'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'usedNullifiers'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >;

    getEvent(key: 'AccessGranted'): TypedContractEvent<AccessGrantedEvent.InputTuple, AccessGrantedEvent.OutputTuple, AccessGrantedEvent.OutputObject>;
getEvent(key: 'AccessRevoked'): TypedContractEvent<AccessRevokedEvent.InputTuple, AccessRevokedEvent.OutputTuple, AccessRevokedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'SemaphoreConfigured'): TypedContractEvent<SemaphoreConfiguredEvent.InputTuple, SemaphoreConfiguredEvent.OutputTuple, SemaphoreConfiguredEvent.OutputObject>;

    filters: {
      
      'AccessGranted(uint256,bytes32)': TypedContractEvent<AccessGrantedEvent.InputTuple, AccessGrantedEvent.OutputTuple, AccessGrantedEvent.OutputObject>;
      AccessGranted: TypedContractEvent<AccessGrantedEvent.InputTuple, AccessGrantedEvent.OutputTuple, AccessGrantedEvent.OutputObject>;
    

      'AccessRevoked(address)': TypedContractEvent<AccessRevokedEvent.InputTuple, AccessRevokedEvent.OutputTuple, AccessRevokedEvent.OutputObject>;
      AccessRevoked: TypedContractEvent<AccessRevokedEvent.InputTuple, AccessRevokedEvent.OutputTuple, AccessRevokedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'SemaphoreConfigured(address,uint256)': TypedContractEvent<SemaphoreConfiguredEvent.InputTuple, SemaphoreConfiguredEvent.OutputTuple, SemaphoreConfiguredEvent.OutputObject>;
      SemaphoreConfigured: TypedContractEvent<SemaphoreConfiguredEvent.InputTuple, SemaphoreConfiguredEvent.OutputTuple, SemaphoreConfiguredEvent.OutputObject>;
    
    };
  }