/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace AgroTypes {
      
    export type FarmerDataStruct = {approved: boolean, riskTier: BigNumberish, cropType: BigNumberish, region: BigNumberish, metadataURI: string}

    export type FarmerDataStructOutput = [approved: boolean, riskTier: bigint, cropType: bigint, region: bigint, metadataURI: string] & {approved: boolean, riskTier: bigint, cropType: bigint, region: bigint, metadataURI: string }
  
    }

  export interface FarmerRegistryInterface extends Interface {
    getFunction(nameOrSignature: "approvedFarmerCount" | "getFarmer" | "getFarmerAt" | "getFarmerCount" | "getFarmers" | "owner" | "registerOrUpdateFarmer" | "renounceOwnership" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "FarmerRegistered" | "FarmerUpdated" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'approvedFarmerCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getFarmer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getFarmerAt', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getFarmerCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getFarmers', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'registerOrUpdateFarmer', values: [AddressLike, boolean, BigNumberish, BigNumberish, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'approvedFarmerCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getFarmer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getFarmerAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getFarmerCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getFarmers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerOrUpdateFarmer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace FarmerRegisteredEvent {
      export type InputTuple = [farmer: AddressLike, data: AgroTypes.FarmerDataStruct];
      export type OutputTuple = [farmer: string, data: AgroTypes.FarmerDataStructOutput];
      export interface OutputObject {farmer: string, data: AgroTypes.FarmerDataStructOutput };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FarmerUpdatedEvent {
      export type InputTuple = [farmer: AddressLike, data: AgroTypes.FarmerDataStruct];
      export type OutputTuple = [farmer: string, data: AgroTypes.FarmerDataStructOutput];
      export interface OutputObject {farmer: string, data: AgroTypes.FarmerDataStructOutput };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface FarmerRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): FarmerRegistry;
    waitForDeployment(): Promise<this>;

    interface: FarmerRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    approvedFarmerCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getFarmer: TypedContractMethod<
      [farmer: AddressLike, ],
      [AgroTypes.FarmerDataStructOutput],
      'view'
    >
    

    
    getFarmerAt: TypedContractMethod<
      [index: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getFarmerCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getFarmers: TypedContractMethod<
      [offset: BigNumberish, limit: BigNumberish, ],
      [string[]],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    registerOrUpdateFarmer: TypedContractMethod<
      [farmer: AddressLike, approved: boolean, riskTier: BigNumberish, cropType: BigNumberish, region: BigNumberish, metadataURI: string, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'approvedFarmerCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getFarmer'): TypedContractMethod<
      [farmer: AddressLike, ],
      [AgroTypes.FarmerDataStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getFarmerAt'): TypedContractMethod<
      [index: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getFarmerCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getFarmers'): TypedContractMethod<
      [offset: BigNumberish, limit: BigNumberish, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'registerOrUpdateFarmer'): TypedContractMethod<
      [farmer: AddressLike, approved: boolean, riskTier: BigNumberish, cropType: BigNumberish, region: BigNumberish, metadataURI: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'FarmerRegistered'): TypedContractEvent<FarmerRegisteredEvent.InputTuple, FarmerRegisteredEvent.OutputTuple, FarmerRegisteredEvent.OutputObject>;
getEvent(key: 'FarmerUpdated'): TypedContractEvent<FarmerUpdatedEvent.InputTuple, FarmerUpdatedEvent.OutputTuple, FarmerUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'FarmerRegistered(address,tuple)': TypedContractEvent<FarmerRegisteredEvent.InputTuple, FarmerRegisteredEvent.OutputTuple, FarmerRegisteredEvent.OutputObject>;
      FarmerRegistered: TypedContractEvent<FarmerRegisteredEvent.InputTuple, FarmerRegisteredEvent.OutputTuple, FarmerRegisteredEvent.OutputObject>;
    

      'FarmerUpdated(address,tuple)': TypedContractEvent<FarmerUpdatedEvent.InputTuple, FarmerUpdatedEvent.OutputTuple, FarmerUpdatedEvent.OutputObject>;
      FarmerUpdated: TypedContractEvent<FarmerUpdatedEvent.InputTuple, FarmerUpdatedEvent.OutputTuple, FarmerUpdatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }