/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface InvestorWhitelistInterface extends Interface {
    getFunction(nameOrSignature: "addInvestor" | "isWhitelisted" | "owner" | "removeInvestor" | "renounceOwnership" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "InvestorAdded" | "InvestorRemoved" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'addInvestor', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isWhitelisted', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'removeInvestor', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'addInvestor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isWhitelisted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeInvestor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace InvestorAddedEvent {
      export type InputTuple = [investor: AddressLike];
      export type OutputTuple = [investor: string];
      export interface OutputObject {investor: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InvestorRemovedEvent {
      export type InputTuple = [investor: AddressLike];
      export type OutputTuple = [investor: string];
      export interface OutputObject {investor: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface InvestorWhitelist extends BaseContract {
    
    connect(runner?: ContractRunner | null): InvestorWhitelist;
    waitForDeployment(): Promise<this>;

    interface: InvestorWhitelistInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addInvestor: TypedContractMethod<
      [investor: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    isWhitelisted: TypedContractMethod<
      [investor: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    removeInvestor: TypedContractMethod<
      [investor: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addInvestor'): TypedContractMethod<
      [investor: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isWhitelisted'): TypedContractMethod<
      [investor: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'removeInvestor'): TypedContractMethod<
      [investor: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'InvestorAdded'): TypedContractEvent<InvestorAddedEvent.InputTuple, InvestorAddedEvent.OutputTuple, InvestorAddedEvent.OutputObject>;
getEvent(key: 'InvestorRemoved'): TypedContractEvent<InvestorRemovedEvent.InputTuple, InvestorRemovedEvent.OutputTuple, InvestorRemovedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'InvestorAdded(address)': TypedContractEvent<InvestorAddedEvent.InputTuple, InvestorAddedEvent.OutputTuple, InvestorAddedEvent.OutputObject>;
      InvestorAdded: TypedContractEvent<InvestorAddedEvent.InputTuple, InvestorAddedEvent.OutputTuple, InvestorAddedEvent.OutputObject>;
    

      'InvestorRemoved(address)': TypedContractEvent<InvestorRemovedEvent.InputTuple, InvestorRemovedEvent.OutputTuple, InvestorRemovedEvent.OutputObject>;
      InvestorRemoved: TypedContractEvent<InvestorRemovedEvent.InputTuple, InvestorRemovedEvent.OutputTuple, InvestorRemovedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }